{"created": 1659442879.7585278, "duration": 0.1569993495941162, "exitcode": 2, "root": "C:\\Users\\jeonghun\\Section3\\ds-sa-simple-git-flow", "environment": {"Python": "3.8.13", "Platform": "Windows-10-10.0.19043-SP0", "Packages": {"pytest": "7.1.2", "py": "1.10.0", "pluggy": "0.13.1"}, "Plugins": {"json-report": "1.5.0", "metadata": "2.0.2", "submit": "1.3.3"}}, "summary": {"total": 0, "collected": 12}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "tests/Part_1.py", "type": "Module"}, {"nodeid": "tests/Part_2.py", "type": "Module"}, {"nodeid": "tests/Part_3.py", "type": "Module"}, {"nodeid": "tests/Part_4.py", "type": "Module"}]}, {"nodeid": "tests/Part_1.py", "outcome": "passed", "result": [{"nodeid": "tests/Part_1.py::test_cli_where_you_are", "type": "Function", "lineno": 6}, {"nodeid": "tests/Part_1.py::test_cli_make_directory", "type": "Function", "lineno": 9}, {"nodeid": "tests/Part_1.py::test_cli_change_direcoty", "type": "Function", "lineno": 12}, {"nodeid": "tests/Part_1.py::test_cli_clone_repo", "type": "Function", "lineno": 15}]}, {"nodeid": "tests/Part_2.py", "outcome": "passed", "result": [{"nodeid": "tests/Part_2.py::test_conda_make_virtual_env", "type": "Function", "lineno": 7}, {"nodeid": "tests/Part_2.py::test_conda_activate_virtual_env", "type": "Function", "lineno": 16}, {"nodeid": "tests/Part_2.py::test_conda_virtual_env_list", "type": "Function", "lineno": 19}, {"nodeid": "tests/Part_2.py::test_conda_if_result_file_exist", "type": "Function", "lineno": 23}]}, {"nodeid": "tests/Part_3.py", "outcome": "passed", "result": [{"nodeid": "tests/Part_3.py::test_git_add_to_staging_area", "type": "Function", "lineno": 6}, {"nodeid": "tests/Part_3.py::test_git_staging_area_statement", "type": "Function", "lineno": 9}, {"nodeid": "tests/Part_3.py::test_git_commit_to_repo", "type": "Function", "lineno": 12}, {"nodeid": "tests/Part_3.py::test_git_push_to_remote", "type": "Function", "lineno": 17}]}, {"nodeid": "tests/Part_4.py", "outcome": "failed", "result": [], "longrepr": "ImportError while importing test module 'C:\\Users\\jeonghun\\Section3\\ds-sa-simple-git-flow\\tests\\Part_4.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n..\\..\\anaconda3\\envs\\s1n1\\lib\\importlib\\__init__.py:127: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\ntests\\Part_4.py:6: in <module>\n    from src import Part_4\nE   ImportError: cannot import name 'Part_4' from 'src' (unknown location)"}], "tests": []}